fullname: pimcore

labels:
  tier: pimcore

autoscaling:
  enabled: true

replicaCount: 1

pullPolicy: Always

serviceAccount: pimcore-deployment-control

pimcore:
  selectorLabels:
    tier: pimcore
    app: pimcore
  php:
    enabled: true
    probe: true
    command: false
    image:
      repository: pimcore
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 4096Mi
        cpu: 500m
  nginx:
    enabled: true
    image:
      repository: nginx
    resources:
      requests:
        memory: 64Mi
        cpu: 125m
      limits:
        memory: 1024Mi
        cpu: 500m
