apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pimcore-public-var
  labels:
    app: pimcore
    role: web
    volumeType: shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
