apiVersion: v1
entries:
  pimcore-deployment:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-10-07T19:01:19.137497716-07:00"
    description: A Helm chart to deploy pimcore to kubernetes. (To be used as a base
      with Kustomize)
    digest: 2ba2d5892cd6640605a97ed788c3b228eb436884b43e4be456602b49776f087a
    name: pimcore-deployment
    type: application
    urls:
    - https://raw.githubusercontent.com/diePartments/pimcore-k8s/develop/base/charts/pimcore-deployment-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-10-07T19:01:19.137277316-07:00"
    description: A Helm chart to deploy pimcore to kubernetes. (To be used as a base
      with Kustomize)
    digest: 0e87f713e5fc4e2e25996afd28ec9de097a444d272ee4db3688ebe469aa9f2f2
    name: pimcore-deployment
    type: application
    urls:
    - https://raw.githubusercontent.com/diePartments/pimcore-k8s/develop/base/charts/pimcore-deployment-0.1.0.tgz
    version: 0.1.0
generated: "2025-10-07T19:01:19.136937214-07:00"
