apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-logger
  labels:
    volumeType: shared
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
