apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-folder
  labels:
    app: pimcore
    volumeType: shared
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
