apiVersion: batch/v1
kind: CronJob
metadata:
  name: pimcore-maintenance
  labels:
    role: mainteance
    tier: cron
    app: pimcore
    lang: php
spec:
  schedule: 00 2 * * *
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes: []
          initContainers: []
          containers:
            - name: php
              command:
                - /bin/bash
              args:
                - -c
                - /var/www/bin/console pimcore:maintenance
              resources:
                requests:
                  memory: 256Mi
                  cpu: 250m
                limits:
                  memory: 4096Mi
                  cpu: 500m
              image: pimcore
              imagePullPolicy: Always
              volumeMounts: []
