apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-deployments
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
